"""full-text search on cases

Adds cases.search_vector, a generated (STORED) tsvector column combining
name + description + last_seen_address, with a GIN index -- lets
case_service.search_cases() do real ranked full-text search (misspellings
within reason, word-stemming, "any of these words" matching) instead of a
plain ILIKE substring match. Generated by Postgres itself on every
insert/update, so it can never drift out of sync with the source columns.

Revision ID: 0015
Revises: 0014
Create Date: 2026-08-10

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import TSVECTOR

revision = "0015"
down_revision = "0014"
branch_labels = None
depends_on = None

SEARCH_VECTOR_EXPRESSION = (
    "to_tsvector('english', "
    "coalesce(name, '') || ' ' || coalesce(description, '') || ' ' || coalesce(last_seen_address, ''))"
)


def upgrade() -> None:
    op.add_column(
        "cases",
        sa.Column(
            "search_vector",
            TSVECTOR,
            sa.Computed(SEARCH_VECTOR_EXPRESSION, persisted=True),
            nullable=True,
        ),
    )
    op.execute("CREATE INDEX ix_cases_search_vector ON cases USING GIN (search_vector)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_cases_search_vector")
    op.drop_column("cases", "search_vector")
